const ERROR_CODES = Object.freeze({
  APP_ERROR: 'APP_ERROR',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  INVALID_PATH: 'INVALID_PATH',
  PATH_OUT_OF_SCOPE: 'PATH_OUT_OF_SCOPE',
  FILE_NOT_FOUND: 'FILE_NOT_FOUND',
  INVALID_FILE_TYPE: 'INVALID_FILE_TYPE',
  INVALID_PROJECT_DIR: 'INVALID_PROJECT_DIR',
  ABSOLUTE_PATH_REJECTED: 'ABSOLUTE_PATH_REJECTED',
  INVALID_PROJECT_FILE: 'INVALID_PROJECT_FILE',
  UNTRUSTED_PROJECT_DIR: 'UNTRUSTED_PROJECT_DIR',
  UNTRUSTED_BACKUP_DIR: 'UNTRUSTED_BACKUP_DIR',
  UNTRUSTED_IPC_SENDER: 'UNTRUSTED_IPC_SENDER',
  INVALID_EXTERNAL_URL: 'INVALID_EXTERNAL_URL',
  INVALID_BACKUP_FILE: 'INVALID_BACKUP_FILE',
  INVALID_EXPORT_FILE_TYPE: 'INVALID_EXPORT_FILE_TYPE',
  INVALID_JSON: 'INVALID_JSON',
  INVALID_PAYLOAD: 'INVALID_PAYLOAD',
  FILE_TOO_LARGE: 'FILE_TOO_LARGE'
});

module.exports = {
  ERROR_CODES
};
